
misc:
  - __target__: picamkit.utils.wait_for
    seconds: 5


# the pipeline of generators
pipeline:
  - __target__: picamkit.ops.control.simple
    max_frames: {{ max_frames | default(10) }}
    fps: {{ frames_per_second | default(5) }}
  - __target__: picamkit.ops.debug.fake_capture
  - __target__: picamkit.ops.sink.save_item
    outdir: {{ output_dir }}
  - __target__: picamkit.ops.sink.save_rgb
    outdir: {{ output_dir }}
