
# the pipeline of generators
pipeline:
  - __target__: picamkit.ops.sources.fs_reader
    idir: {{ image_dir }}
  - __target__: picamkit.ops.imaging.scale
    factor: 0.5
  - __target__: picamkit.ops.io.save_rgb
    outdir: {{ output_dir }}
