
# the pipeline of generators
pipeline:
  - __target__: picamkit.ops.source.fs_reader
    idir: {{ image_dir }}
    recursive: True
  - __target__: picamkit.ops.imaging.scale
    factor: 0.5
  - __target__: picamkit.ops.sink.save_rgb
    outdir: {{ output_dir }}
