# the camera
camera:
  __target__: picamkit.camera.Camera
  camera_id: {{ camera_id | default(0) }}
  mode: {{ camera_mode | default(5) }}
  vflip: false
  hflip: false
  preview: true
  min_frameduration: {{ 1000000.0 / (frames_per_second | default(5) | float) }}
  tuning_file: {{ tuning_file | default('imx219_noir.json') }}


# configure the camera
configure_cam:
  - __target__: picamkit.camera.set_whitebalance
    camera:
      __instance__: camera
    mode:
      __enum__: picamkit.camera.AwbModeEnum.AUTO
  - __target__: picamkit.camera.set_exposure
    camera:
      __instance__: camera
    metering_mode:
      __enum__: picamkit.camera.MeteringModeEnum.CENTRE_WEIGHTED
    wait: true


# the pipeline of generators
pipeline:
  - __target__: picamkit.ops.control.simple
  - __target__: picamkit.ops.camera.capture
    camera:
      __instance__: camera
    arrays:
      - main
    immediate: true
  - __target__: picamkit.ops.debug.dump
    key: metadata
    interval: {{ (max_frames | default(100) | int ) - 1 }}
