

# the pipeline of generators
pipeline:
  - __target__: picamkit.ops.sources.s3_reader
    profile_name: {{ profile_name | default('default') }}
    bucket: {{ bucket }}
    prefix: {{ bucket_prefix }}
  - __target__: picamkit.ops.imaging.scale
    factor: 0.5
  - __target__: picamkit.ops.sink.save_rgb
    outdir: {{ output_dir }}

